var RMT_0        = 48;
var RMT_1        = 49;
var RMT_2        = 50;
var RMT_3        = 51;
var RMT_4        = 52;
var RMT_5        = 53;
var RMT_6        = 54;
var RMT_7        = 55;
var RMT_8        = 56;
var RMT_9        = 57;
var RMT_CR       = 13;
var RMT_OK       = 13;
var RMT_PLAY     = 80;   // P
var RMT_PAUSE    = 80;   // P
var RMT_FF       = 190;  // >
var RMT_RW       = 188;  // <
var RMT_STOP     = 88;   // X
var RMT_STOP2    = 0;
var RMT_RED      = 82;   // R
var RMT_GREEN    = 71;   // G
var RMT_YELLOW   = 89;   // Y
var RMT_BLUE     = 66;   // B
var RMT_HELP     = 72;   // H
var RMT_HELP2    = 72;   // H
var RMT_ASTERISK = 0;
var RMT_PGFWD    = 0;
var RMT_PGBACK   = 0;
var RMT_PGFWD2   = 0;
var RMT_PGBACK2  = 0;
var RMT_VOLUP    = 221;  // }
var RMT_VOLDOWN  = 219;  // {
var RMT_POWER    = 0;
var RMT_MUTE     = 109;  // -
var RMT_UP       = 38;   // up arrow
var RMT_DOWN     = 40;   // down arrow
var RMT_LEFT     = 37;   // left arrow
var RMT_RIGHT    = 39;   // right arrow
var RMT_MOVIES   = 66;   // B
var RMT_CHUP     = 81;   // Q
var RMT_CHDN     = 90;   // Z
var RMT_HASH     = 0;
var RMT_INFO     = 73;   // I
var RMT_MENU     = 0;
var RMT_BACK     = 0;
var RMT_TITLES   = 0;
var RMT_TITLES2  = 0;
var RMT_EPG      = 69; // E
var RMT_TV       = 0;
var RMT_SOURCE   = 78; // N
var RMT_INPUT    = 78; // N
var RMT_EXIT     = 0;
// 0 = no function in chrome
