var RMT_0        = hcap.key.Code.NUM_0;
var RMT_1        = hcap.key.Code.NUM_1;
var RMT_2        = hcap.key.Code.NUM_2;
var RMT_3        = hcap.key.Code.NUM_3;
var RMT_4        = hcap.key.Code.NUM_4;
var RMT_5        = hcap.key.Code.NUM_5;
var RMT_6        = hcap.key.Code.NUM_6;
var RMT_7        = hcap.key.Code.NUM_7;
var RMT_8        = hcap.key.Code.NUM_8;
var RMT_9        = hcap.key.Code.NUM_9;
var RMT_CR       = hcap.key.Code.ENTER;
var RMT_OK       = hcap.key.Code.ENTER;
var RMT_PLAY     = hcap.key.Code.PLAY;
var RMT_PAUSE    = hcap.key.Code.PAUSE;
var RMT_FF       = hcap.key.Code.FAST_FORWARD;
var RMT_RW       = hcap.key.Code.REWIND;
var RMT_STOP     = hcap.key.Code.STOP;
var RMT_STOP2    = 0;
var RMT_RED      = hcap.key.Code.RED;
var RMT_GREEN    = hcap.key.Code.GREEN;
var RMT_YELLOW   = hcap.key.Code.YELLOW;
var RMT_BLUE     = hcap.key.Code.BLUE;
var RMT_HELP     = 0;
var RMT_HELP2    = 0;
var RMT_ASTERISK = 0;
var RMT_PGFWD    = 999;
var RMT_PGBACK   = 999;
var RMT_PGFWD2   = 999;
var RMT_PGBACK2  = 999;
var RMT_VOLUP    = hcap.key.Code.VOL_UP;
var RMT_VOLDOWN  = hcap.key.Code.VOL_DOWN;
var RMT_POWER    = hcap.key.Code.POWER;
var RMT_MUTE     = hcap.key.Code.MUTE;
var RMT_UP       = hcap.key.Code.UP;
var RMT_DOWN     = hcap.key.Code.DOWN;
var RMT_LEFT     = hcap.key.Code.LEFT;
var RMT_RIGHT    = hcap.key.Code.RIGHT;
var RMT_MOVIES   = hcap.key.Code.PORTAL;
var RMT_CHUP     = hcap.key.Code.CH_UP;   // works in firmware 7.06+
var RMT_CHDN     = hcap.key.Code.CH_DOWN; // works in firmware 7.06+
//var RMT_CHUP     = hcap.key.Code.PAGE_UP;
//var RMT_CHDN     = hcap.key.Code.PAGE_DOWN;
var RMT_HASH     = 0;
var RMT_INFO     = hcap.key.Code.INFO;
var RMT_MENU     = hcap.key.Code.PORTAL; // works in firmware 7.06+
//var RMT_MENU     = 189; // PORTAL key (not mapped correctly?) - is 601 in firmware 7.06+
var RMT_BACK     = hcap.key.Code.BACK;
var RMT_TITLES   = 0; // Is native key..
var RMT_TITLES2  = 0;
var RMT_EPG      = 458; // Note: hcap.key.Code.GUIDE is NOT this code..
var RMT_TV       = 0;
var RMT_SOURCE   = 0;
var RMT_INPUT    = 0;
var RMT_EXIT     = hcap.key.Code.EXIT; // 1001;
// hcap.key.Code.* == LGE CONSTANTS
